### ISSUE TITLE
Integration Tab has no settings on it

### ISSUE THREAD

**Issue by foxinni** [woothemes/woocommerce-google-analytics-integration#43] opened 2015-02-25 10:11 UTC
I installed the analytics integration plugin and when I navigate to the Integration tab there is no settings, just the save button.

Any ideas?

**Comment by justinshreve** [comment] 2015-06-24 17:08
Hi @foxinni - I can't seem to reproduce this. Can you let me know which version of WooCommerce and which version of the Google Analytics plugin you are using?

**Comment by justinshreve** [comment] 2015-06-29 14:43
Closing this since we can't produce + I don't see anything in the code that would cause this as long as the plugin is activated. If you are still having this issue, please let us know what versions you are using.

**Closed by justinshreve** 2015-06-29 14:43 UTC
Labels: bug

**Comment by foxinni** [comment] 2015-06-29 14:51
Hey,

I installed again now and seems to be working. Not sure what changed exactly. Thanks for the follow up.
